name: cafe_amba
description: Aplikasi pemesanan cafe untuk pelanggan, kitchen, dan kasir
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  shared_preferences: ^2.2.2
  google_fonts: ^8.1.0 # naikkan dari ^6.1.0
  image_picker: ^1.1.2 # upload bukti pembayaran (galeri)
  gal: ^2.3.0 # "Unduh QRIS" → simpan gambar ke galeri
  fl_chart: ^1.2.0
  http: ^1.2.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0 # naikkan dari ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/menu/
    - assets/payment/
